version: '3'
services:
  web:
    image: php:8.2-apache
    ports:
      - "${HTTP_PORT:-80}:80"    # Uses HTTP_PORT from .env, defaults to 80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    command: bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"
    restart: unless-stopped    # Helps with automatic recovery

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
    name: ${COMPOSE_PROJECT_NAME:-my_project}_mysql    # Named volume for easier management