<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'reservation_id',
'comments',
'firstname',
'lastname',
'phone',
'mobile',
'zipcode',
'locationId',
'treatmentId',
'rsvDate',
'rsvTime',
'rsvStatus',
'createdAt',
'updatedAt',
'changesCount',
'displayName' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'reservation_id' => array( 'import_field' ),
'firstname' => array( 'import_field1' ),
'phone' => array( 'import_field3' ),
'mobile' => array( 'import_field4' ),
'zipcode' => array( 'import_field5' ),
'locationId' => array( 'import_field6' ),
'treatmentId' => array( 'import_field7' ),
'rsvDate' => array( 'import_field8' ),
'rsvTime' => array( 'import_field9' ),
'rsvStatus' => array( 'import_field10' ),
'createdAt' => array( 'import_field11' ),
'changesCount' => array( 'import_field12' ),
'updatedAt' => array( 'import_field13' ),
'comments' => array( 'import_field15' ),
'lastname' => array( 'import_field2' ),
'displayName' => array( 'import_field14' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field15',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field13',
'import_field12',
'import_field14' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field15' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field13' => 'grid',
'import_field12' => 'grid',
'import_field14' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field15',
'import_field2',
'import_field14' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field15',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field13',
'import_field12',
'import_field14' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'reservation_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'firstname',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'phone',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'mobile',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'zipcode',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'locationId',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'treatmentId',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'rsvDate',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'rsvTime',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'rsvStatus',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'createdAt',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'changesCount',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'updatedAt',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'comments',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'lastname',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'displayName',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>